"""Markdown report for the frontend.

Figures come only from the deterministic summaries. Narrative from the LLM is
labelled as generated and escaped like any other untrusted text, so it cannot
inject links, HTML or table structure.
"""

from datetime import datetime, timezone
from decimal import Decimal
import re
from typing import Any, Dict, Iterable, List, Optional


_MD_SPECIAL = re.compile(r"([\\`*_{}\[\]<>()#+!|~])")
_WS = re.compile(r"\s+")

PRETTY = {
    "outward": "Outward supplies (sales, exports)", "inward": "Inward supplies (purchases, imports)",
    "credit_notes": "Credit notes (sales returns)", "debit_notes": "Debit notes (purchase returns)",
    "receipts": "Receipts", "payments": "Payments", "expenses": "Expenses", "other": "Other voucher types",
}
LIMITATIONS = [
    "Figures are computed only from the supplied rows; no ledger, bank, GSTR-2B or GST portal data was used.",
    "Voucher categories come from a statistical classifier and may be wrong; category-dependent totals inherit that risk.",
    "Input tax credit is shown only as a potential amount with basic evidence; legal eligibility is not determined.",
    "This report is not a GST return, has not been filed, and is not tax advice.",
]


def esc(value: Any) -> str:
    """Escape untrusted text for inline Markdown (also safe inside table cells)."""
    text = _WS.sub(" ", "" if value is None else str(value)).strip()
    return _MD_SPECIAL.sub(r"\\\1", text)


def money(value: Optional[str], currency: str = "INR") -> str:
    if value is None:
        return "—"
    return f"{currency} {Decimal(value):,.2f}"


_ACRONYMS = {"gst", "cgst", "sgst", "igst", "itc", "b2b"}


def pretty(name: str) -> str:
    words = [w.upper() if w in _ACRONYMS else w for w in name.split("_")]
    text = " ".join(words)
    return text[:1].upper() + text[1:]


def _table(headers: List[str], rows: Iterable[List[str]]) -> List[str]:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return lines


def _calc_rows(calcs: List[Dict[str, Any]]) -> List[List[str]]:
    return [[esc(pretty(c["name"])), money(c["value"], c["currency"]), c["status"],
             f"{c['rows_included']} used / {c['rows_missing']} missing"] for c in calcs]


def _bullets(items: Iterable[str], prefix: str = "") -> List[str]:
    return [f"- {prefix}{esc(i)}" for i in items]


def render_report(state: Dict[str, Any]) -> str:
    acc = state.get("accounting_summary", {})
    gst = state.get("gst_summary", {})
    discrepancies = state.get("discrepancies", [])
    readiness = state.get("filing_readiness", {})
    analysis = state.get("llm_analysis")
    llm_meta = state.get("llm_meta", {})
    currency = acc.get("base_currency", "INR")
    generated = analysis is not None
    narrative_source = (f"generated by {esc(llm_meta.get('model'))} (Groq); figures in tables are authoritative"
                        if generated else "deterministic fallback; no generated narrative")

    out: List[str] = ["# GST Intelligence Report", ""]
    out += [f"**Status:** {state.get('status')} · **Filing readiness:** {readiness.get('level', '—')} · "
            f"**Request:** `{esc(state.get('request_id'))}`",
            f"**Input:** {esc(state.get('input_type'))}, {acc.get('transaction_count', 0)} rows · "
            f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} · **Narrative:** {narrative_source}",
            "",
            "> Prepared for review only. Not a filed return, not reconciled with the GST portal or GSTR-2B, and not tax advice.",
            ""]

    # Executive summary
    out += ["## Executive Summary", ""]
    if generated:
        out += [esc(analysis["executive_summary"]), ""]
    else:
        high = sum(1 for d in discrepancies if d["severity"] == "HIGH")
        net = next((c for c in gst.get("calculations", []) if c["name"] == "potential_net_gst_liability"), None)
        groups_word = "group was" if len(discrepancies) == 1 else "groups were"
        out += [f"{acc.get('transaction_count', 0)} rows were analysed. {len(discrepancies)} discrepancy {groups_word} "
                f"found ({high} high severity). Potential net GST liability: "
                f"{money(net['value'], currency) if net else '—'} ({net['status'] if net else 'not computed'}).", ""]
        if llm_meta.get("message"):
            out += [f"_{esc(llm_meta['message'])}_", ""]

    # Accounting summary
    out += ["## Accounting Summary", ""]
    groups = acc.get("counts_by_group", {})
    out += _table(["Voucher group", "Rows"], [[PRETTY.get(g, g), str(n)] for g, n in groups.items()]) + [""]
    if acc.get("rows_excluded_foreign_currency"):
        out += [f"{acc['rows_excluded_foreign_currency']} rows in other currencies were excluded from totals.", ""]
    if acc.get("rows_with_assumed_base_currency"):
        out += [f"{acc['rows_with_assumed_base_currency']} rows stated no currency and were treated as {currency}.", ""]
    out += _table(["Figure", "Value", "Status", "Rows"], _calc_rows(acc.get("calculations", []))) + [""]
    balance = state.get("balance_summary", {})
    if balance.get("available"):
        out += ["**Ledger balances** (" + esc(balance["sign_convention"]) + ")", ""]
        out += _table(["Ledger", "Opening", "Debits", "Credits", "Closing (reported)", "Closing (computed)", "Reconciles"],
                      [[esc(l["ledger"]), money(l["opening"], currency), money(l["debits"], currency),
                        money(l["credits"], currency), money(l["closing_reported"], currency),
                        money(l["closing_computed_debit_positive"], currency), str(l["reconciles"])]
                       for l in balance["ledgers"]]) + ["", esc(balance["note"]), ""]
    else:
        out += [f"**Balance sheet:** not produced. {esc(balance.get('reason', ''))}", ""]
    if generated and analysis["accounting_observations"]:
        out += ["**Observations (generated):**"] + _bullets(analysis["accounting_observations"]) + [""]

    # GST summary
    out += ["## GST Summary", ""]
    calcs = [c for c in gst.get("calculations", []) if not (c["status"] == "NOT_APPLICABLE" and c["value"] == "0.00")]
    out += _table(["Figure", "Value", "Status", "Rows"], _calc_rows(calcs)) + [""]
    out += ["Net liability and ITC are **potential** figures; eligibility, blocked credits, reversals and portal "
            "reconciliation are not evaluated.", ""]
    if generated and analysis["gst_observations"]:
        out += ["**Observations (generated):**"] + _bullets(analysis["gst_observations"]) + [""]

    # Discrepancies
    out += ["## Discrepancy Report", ""]
    if not discrepancies:
        out += ["No discrepancies were detected by the configured checks.", ""]
    else:
        out += _table(["Code", "Severity", "Status", "Rows", "Finding"],
                      [[f"`{esc(d['code'])}`", d["severity"], d["status"],
                        str(d["evidence"].get("affected_rows", len(d["source_rows"]))), esc(d["message"])]
                       for d in discrepancies]) + [""]
        explanations = {e["code"]: e for e in (analysis or {}).get("discrepancy_explanations", [])}
        for d in discrepancies:
            out += [f"**{esc(d['code'])}** ({d['severity']}, {d['status']}). Rows: "
                    f"{esc(', '.join(d['source_rows'][:10])) or '—'}"
                    + (" …" if len(d["source_rows"]) > 10 else ""),
                    f"- Action: {esc(d['recommended_action'])}"]
            if d["code"] in explanations:
                e = explanations[d["code"]]
                out += [f"- Explanation (generated): {esc(e['explanation'])}",
                        f"- Why it matters (generated): {esc(e['why_it_matters'])}"]
            out.append("")

    # Filing preparation
    out += ["## Filing Preparation Data", ""]
    prep = state.get("filing_preparation", {})
    rows = []
    for key, section in prep.items():
        if key == "note":
            continue
        if key == "outward_without_valid_recipient_gstin":
            for rate, s in section.items():
                rows.append([f"Outward without valid recipient GSTIN, rate {esc(rate)}", str(s["rows"]),
                             money(s.get("taxable_value"), currency), money(s.get("tax"), currency), s["status"]])
            if not section:
                rows.append(["Outward without valid recipient GSTIN", "0", "—", "—", "NO_DATA"])
            continue
        rows.append([esc(pretty(key)), str(section["rows"]), money(section.get("taxable_value"), currency),
                     money(section.get("tax"), currency), section["status"]])
    out += _table(["Section", "Rows", "Taxable value", "Tax", "Status"], rows) + ["", esc(prep.get("note", "")), ""]

    # Actions
    out += ["## Recommended Actions", ""]
    actions = []
    for d in discrepancies:
        if d["severity"] in ("HIGH", "MEDIUM") and d["recommended_action"] not in actions:
            actions.append(d["recommended_action"])
    out += _bullets(actions) if actions else ["- No corrective actions from the configured checks."]
    if generated and analysis["recommended_actions"]:
        out += ["", "**Further suggestions (generated):**"] + _bullets(analysis["recommended_actions"])
    out.append("")

    # Missing information and limitations
    out += ["## Missing Information and Limitations", ""]
    missing = state.get("missing_fields", [])
    if missing:
        out += _table(["Field", "Needed for", "Rows missing"],
                      [[esc(m["field"]), esc(m["required_for"]), str(m["rows_missing"])] for m in missing]) + [""]
    if generated and analysis["missing_information"]:
        out += ["**Missing information (generated):**"] + _bullets(analysis["missing_information"]) + [""]
    out += ["**Assumptions:**"] + _bullets(state.get("assumptions", [])) + [""]
    out += ["**Limitations:**"] + _bullets(LIMITATIONS)
    if generated and analysis["limitations"]:
        out += _bullets(analysis["limitations"], prefix="(generated) ")
    warnings = state.get("warnings", [])
    if warnings:
        out += ["", "**Processing warnings:**"] + _bullets(warnings)
    out.append("")

    # Readiness
    out += ["## Filing Readiness", "", f"**{readiness.get('level', '—')}**", ""]
    out += _bullets(readiness.get("reasons", [])) + ["", esc(readiness.get("note", "")), ""]
    return "\n".join(out)


def render_error_report(request_id: str, errors: List[str]) -> str:
    lines = ["# GST Intelligence Report", "", "**Status:** PROCESSING_FAILED", "", "## Input could not be analysed", ""]
    lines += _bullets(errors)
    lines += ["", f"Request: `{esc(request_id)}`", ""]
    return "\n".join(lines)
