import { Transaction, UploadRecord, ValidationCheck } from './types';

export const MOCK_UPLOADS: UploadRecord[] = [
  {
    id: 'up-1',
    filename: 'October_Transactions.xlsx',
    rows: '12,450 rows',
    status: 'Completed',
    date: '12 Oct 2024',
  },
  {
    id: 'up-2',
    filename: 'Sales_Data.xlsx',
    rows: '8,210 rows',
    status: 'Processing',
    date: '11 Oct 2024',
  },
  {
    id: 'up-3',
    filename: 'Q3_Books.csv',
    rows: '5,434 rows',
    status: 'Failed',
    date: '10 Oct 2024',
  },
];

export const MOCK_VALIDATION_CHECKS: ValidationCheck[] = [
  { id: '1', label: 'File readable', status: 'passed', iconType: 'check' },
  { id: '2', label: 'Required columns detected', status: 'passed', iconType: 'check' },
  { id: '3', label: 'Date format valid', status: 'passed', iconType: 'check' },
  { id: '4', label: 'Amount fields valid', status: 'passed', iconType: 'check' },
  { id: '5', label: '23 missing GSTIN values', status: 'warning', iconType: 'warning' },
  { id: '6', label: '8 duplicate invoice numbers', status: 'warning', iconType: 'warning' },
  { id: '7', label: 'All other fields valid', status: 'passed', iconType: 'check' },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    invoiceNo: 'INV-1024',
    date: '12 Oct 2024',
    party: 'ABC Traders',
    amount: '₹42,500',
    rawAmount: 42500,
    predictedVoucher: 'Purchase',
    confidence: 97,
    status: 'High',
    gstin: '27AABCT4321A1Z8',
    taxableValue: '₹36,017',
    gstAmount: '₹6,483',
    paymentMode: 'Net Banking',
    description: 'Bulk raw material procurement - Steel plates',
    sourceFile: 'October_Transactions.xlsx',
    topCandidates: [
      { voucher: 'Purchase', confidence: 97 },
      { voucher: 'Expense', confidence: 2 },
      { voucher: 'Payment', confidence: 1 },
    ],
    aiAnalysis: {
      classificationBasis: 'Line items match registered GST purchase ledger and input tax credit eligibility criteria.',
      candidateComparison: 'Categorized under Purchase rather than Expense as the items form part of core direct inventory.',
      confidenceFactors: ['Vendor GSTIN active', 'Inventory HSN detected (7208)', 'Purchase order matched'],
      detectedSignals: ['GST 18% slab validated', 'ITC eligible', 'Direct cost classification'],
    },
  },
  {
    id: 'tx-2',
    invoiceNo: 'INV-1025',
    date: '12 Oct 2024',
    party: 'XYZ Ltd',
    amount: '₹18,200',
    rawAmount: 18200,
    predictedVoucher: 'Sales',
    confidence: 94,
    status: 'High',
    gstin: '27XYZLL9876K1ZP',
    taxableValue: '₹15,424',
    gstAmount: '₹2,776',
    paymentMode: 'UPI',
    description: 'Finished goods distribution to Western zone dealer',
    sourceFile: 'October_Transactions.xlsx',
    topCandidates: [
      { voucher: 'Sales', confidence: 94 },
      { voucher: 'Journal', confidence: 4 },
      { voucher: 'Payment', confidence: 2 },
    ],
    aiAnalysis: {
      classificationBasis: 'Outward taxable supply transaction with debit to customer ledger and credit to revenue account.',
      candidateComparison: 'High correlation with historical outward sales receipts and automated e-way bill generation pattern.',
      confidenceFactors: ['Customer master record', 'Outward tax ledger', 'Serial invoice sequence'],
      detectedSignals: ['GSTR-1 auto-population match', 'B2B supply', 'Standard tax rate applied'],
    },
  },
  {
    id: 'tx-3',
    invoiceNo: 'INV-1026',
    date: '11 Oct 2024',
    party: 'PQR Corp',
    amount: '₹8,900',
    rawAmount: 8900,
    predictedVoucher: 'Payment',
    confidence: 89,
    status: 'High',
    gstin: '27PQRCP1122M1ZQ',
    taxableValue: '₹8,900',
    gstAmount: '₹0',
    paymentMode: 'Bank Transfer',
    description: 'Vendor payment settlement for September billing',
    sourceFile: 'October_Transactions.xlsx',
    topCandidates: [
      { voucher: 'Payment', confidence: 89 },
      { voucher: 'Expense', confidence: 8 },
      { voucher: 'Journal', confidence: 3 },
    ],
    aiAnalysis: {
      classificationBasis: 'Bank debit reference matching outstanding accounts payable balance without fresh tax liability.',
      candidateComparison: 'Payment voucher confirmed due to absence of reverse charge or new supply generation.',
      confidenceFactors: ['Bank statement counterparty', 'Outstanding invoice knocked off', 'No fresh ITC claim'],
      detectedSignals: ['NEFT narration matched', 'Creditor account debit', 'Zero GST component'],
    },
  },
  {
    id: 'tx-4',
    invoiceNo: 'INV-1027',
    date: '11 Oct 2024',
    party: 'LMN Enterprises',
    amount: '₹31,000',
    rawAmount: 31000,
    predictedVoucher: 'Expense',
    confidence: 61,
    status: 'Review',
    gstin: '27ABCDE1234F1Z5',
    taxableValue: '₹26,271',
    gstAmount: '₹4,729',
    paymentMode: 'Credit',
    description: 'Office furniture purchase',
    sourceFile: 'October_Transactions.xlsx',
    topCandidates: [
      { voucher: 'Expense', confidence: 61 },
      { voucher: 'Purchase', confidence: 34 },
      { voucher: 'Payment', confidence: 5 },
    ],
    aiAnalysis: {
      classificationBasis: 'Transaction description and accounting context indicate an operating expense.',
      candidateComparison: 'Expense was preferred over Purchase because the transaction does not contain strong inventory acquisition signals.',
      confidenceFactors: ['Party type', 'Transaction description', 'Amount pattern', 'Payment context'],
      detectedSignals: ['GSTIN verified (Maharashtra)', 'HSN 9403: Office Furniture', 'Non-inventory capital expenditure'],
    },
  },
  {
    id: 'tx-5',
    invoiceNo: 'INV-1028',
    date: '10 Oct 2024',
    party: 'DEF Ltd',
    amount: '₹15,600',
    rawAmount: 15600,
    predictedVoucher: 'Journal',
    confidence: 72,
    status: 'High',
    gstin: '27DEFLL3344J1ZN',
    taxableValue: '₹13,220',
    gstAmount: '₹2,380',
    paymentMode: 'Adjustment',
    description: 'Quarterly credit note rebate and inventory valuation adjustment',
    sourceFile: 'October_Transactions.xlsx',
    topCandidates: [
      { voucher: 'Journal', confidence: 72 },
      { voucher: 'Sales', confidence: 18 },
      { voucher: 'Expense', confidence: 10 },
    ],
    aiAnalysis: {
      classificationBasis: 'Non-cash ledger balancing adjustment affecting multiple fiscal accounts.',
      candidateComparison: 'Journal entry assigned rather than Sales due to credit adjustment characteristics.',
      confidenceFactors: ['Inter-ledger reconciliation', 'Non-bank transaction', 'Rebate credit note schema'],
      detectedSignals: ['Contra reference', 'GSTR-2B discrepancy resolution', 'Accrual reversal'],
    },
  },
  {
    id: 'tx-6',
    invoiceNo: 'INV-1029',
    date: '10 Oct 2024',
    party: 'Sterling Tech Services',
    amount: '₹74,200',
    rawAmount: 74200,
    predictedVoucher: 'Expense',
    confidence: 95,
    status: 'High',
    gstin: '27STELT5566R1ZT',
    taxableValue: '₹62,881',
    gstAmount: '₹11,319',
    paymentMode: 'Credit Card',
    description: 'Cloud infrastructure annual hosting and security audit license',
    sourceFile: 'October_Transactions.xlsx',
    topCandidates: [
      { voucher: 'Expense', confidence: 95 },
      { voucher: 'Purchase', confidence: 3 },
      { voucher: 'Payment', confidence: 2 },
    ],
    aiAnalysis: {
      classificationBasis: 'Software as a Service operating expense with valid SAC code 998315.',
      candidateComparison: 'Expense strongly confirmed over Purchase due to service nature without tangible goods movement.',
      confidenceFactors: ['SAC service code', 'Recurring SaaS billing pattern', 'RCM exemption validated'],
      detectedSignals: ['GST 18% verified', 'Tax invoice compliant', 'P&L administrative cost'],
    },
  },
  {
    id: 'tx-7',
    invoiceNo: 'INV-1030',
    date: '09 Oct 2024',
    party: 'Bharat Petroleum Corp',
    amount: '₹12,850',
    rawAmount: 12850,
    predictedVoucher: 'Expense',
    confidence: 91,
    status: 'High',
    gstin: '27BPCLG9900H1ZB',
    taxableValue: '₹12,850',
    gstAmount: '₹0',
    paymentMode: 'Fleet Card',
    description: 'Corporate logistics fleet diesel refuel vouchers',
    sourceFile: 'October_Transactions.xlsx',
    topCandidates: [
      { voucher: 'Expense', confidence: 91 },
      { voucher: 'Payment', confidence: 7 },
      { voucher: 'Purchase', confidence: 2 },
    ],
    aiAnalysis: {
      classificationBasis: 'Non-GST petroleum product expenditure categorized directly under fleet travel & conveyance.',
      candidateComparison: 'Expense selected with zero ITC ledger credit as per GST schedule provisions.',
      confidenceFactors: ['Non-ITC eligible fuel', 'Direct travel head', 'Company vehicle fleet linked'],
      detectedSignals: ['VAT exempt invoice', 'Operational overhead', 'Fleet telematics timestamp match'],
    },
  },
  {
    id: 'tx-8',
    invoiceNo: 'INV-1031',
    date: '09 Oct 2024',
    party: 'Orbit Global Logistics',
    amount: '₹54,000',
    rawAmount: 54000,
    predictedVoucher: 'Purchase',
    confidence: 64,
    status: 'Review',
    gstin: '27ORBIT8877P1ZV',
    taxableValue: '₹51,428',
    gstAmount: '₹2,572',
    paymentMode: 'Net Banking',
    description: 'Interstate freight shipping and warehousing consignments',
    sourceFile: 'October_Transactions.xlsx',
    topCandidates: [
      { voucher: 'Purchase', confidence: 64 },
      { voucher: 'Expense', confidence: 31 },
      { voucher: 'Payment', confidence: 5 },
    ],
    aiAnalysis: {
      classificationBasis: 'Freight inward service directly related to raw material transport, eligible for capitalization.',
      candidateComparison: 'Requires human confirmation on whether freight is allocated to stock value or written off as freight expense.',
      confidenceFactors: ['GTA consignment note attached', 'Reverse charge applicability query', 'Threshold validation'],
      detectedSignals: ['GTA 5% GST rate detected', 'RCM review flagged', 'Interstate e-way consignment'],
    },
  },
];
